dropout: 0.5
epochs: 2000
hid_dim: 32
lr: 0.01
model_name: GAT_fuse_embed
nlayers: 2
patience: 5
ratio_fc: 0.8
ratio_sc: 0.8
reduce: mean
reduce_fuse: mean
split_args:
  test_size: 0.2
  train_size: 0.6
  valid_size: 0.2
use_wandb: true
wd: 0.01