attn_weight: true
dropout: 0.5
epochs: 2000
file_option: _miss_graph
fuse_type: unit_miss
hid_dim: 128
lr: 0.01
model_name: MewCustom
nlayers: 3
patience: 5
reduce: mean
shared: true
split_args:
    test_size: 0.2
    train_size: 0.6
    valid_size: 0.2
use_wandb: true
wd: 0.01