combine_type: attn_weight
dropout: 0.5
epochs: 2000
file_option: _miss_graph_miss_label
fuse_method: GAT
fuse_on: node_embed
hid_dim: 128
knn_on: graph_embed
lr: 0.01
model_name: MHGCNFuseGraph
nlayers: 3
patience: 5
reduce: mean
shared: false
split_args:
    test_size: 0.2
    train_size: 0.6
    valid_size: 0.2
supp_k: 2
use_wandb: true
wd: 0.01