dropout: 0.5
epochs: 2000
hid_dim: 64
lr: 0.001
model_name: SGC_fuse_embed_nosia
nlayers: 2
patience: 5
ratio: 0.2
ratio_fc: 0.8
ratio_sc: 0.8
reduce: mean
reduce_fuse: concat
split_args:
  test_size: 0.2
  train_size: 0.6
  valid_size: 0.2
use_wandb: true
wd: 0.01