dropout: 0.5
epochs: 2000
hid_dim: 128
lr: 0.01
modality: sc
model_name: SGC
nlayers: 2
patience: 5
ratio: 0.8
ratio_fc: 0.5
ratio_sc: 0.1
reduce: mean
split_args:
    test_size: 0.2
    train_size: 0.6
    valid_size: 0.2
use_wandb: true
wd: 0.01